server:
   port: 9090

spring:
  application:
    name: spring-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ai-db
    username: spring-ai-usr
    password: springai123
  ai:
    openai:
      api-key: sk-proj-jr7aUQLfWdIjynT5Uhx6T3BlbkFJ5hV2NBmLutxYkmmOTO5c
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: start_only
#  main:
#    banner-mode: off
#logging:
#  level:
#    root: off